version: 0.2
phases:
  install:
    commands:
      - echo "Start Install"
      - echo $(date)
      - echo "End Install"
  build:
    commands:
      - echo "Start Build"
      - echo $(date)
      - |
        if aws cloudformation describe-stacks --stack-name fmaric-dynamodb; then
          echo "Stack exists, deleting..."
          aws cloudformation delete-stack --stack-name fmaric-dynamodb
          aws cloudformation wait stack-delete-complete --stack-name fmaric-dynamodb
        fi
      - aws cloudformation deploy --template-file CICD/s3.yml --stack-name fmaric-s3 --parameter-overrides S3BucketData="fmaric-data-bucket-cf" S3BucketScripts="fmaric-scripts-bucket-cf" --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - aws cloudformation deploy --template-file CICD/dynamodb.yml --stack-name fmaric-dynamodb --parameter-overrides DynamoDBTableGlobalName="fmaric-academy-global-cloudf" DynamoDBTableJobsName="fmaric-academy-jobs-cloudf" --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - |
        if aws cloudformation describe-stacks --stack-name fmaric-statemachine-stack; then
          STACK_STATUS=$(aws cloudformation describe-stacks --stack-name fmaric-statemachine-stack --query "Stacks[0].StackStatus" --output text)
          if [ "$STACK_STATUS" == "ROLLBACK_FAILED" ] || [ "$STACK_STATUS" == "ROLLBACK_COMPLETE" ]; then
            echo "Stack is in $STACK_STATUS state, deleting..."
            aws cloudformation delete-stack --stack-name fmaric-statemachine-stack
            aws cloudformation wait stack-delete-complete --stack-name fmaric-statemachine-stack
          fi
        fi

      - zip -r fmaric-academy-lambda-cf.zip RESOURCES/fmaric-academy-lambda-cf.py
      - aws cloudformation deploy --template-file CICD/s3.yml --stack-name fmaric-s3-stack
      - aws s3 cp fmaric-academy-lambda-cf.zip s3://fmaric-academy-scripts-cf
      - aws cloudformation deploy --template-file CICD/dynamodb.yml --stack-name fmaric-dynamodb-stack
      - aws cloudformation deploy --template-file CICD/statemachine.yml --stack-name fmaric-state-machine-stack --capabilities CAPABILITY_NAMED_IAM
      - echo "End Build"