version: 0.2

phases:
  install:
    commands:
      - echo "Start Install"
      - echo $(date)
      - echo "End Install"

  build:
    commands:
      - echo "Start Build"
      - echo $(date)
      - aws cloudformation deploy --template-file CICD/s3.yml --stack-name fmarc-s3 --parameter-overrides S3BucketData="fmarc-academy-aws-data-cf" S3BucketScripts="fmarc-academy-aws-scripts-cf" --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - aws cloudformation deploy --template-file CICD/dynamodb.yml --stack-name fmarc-dynamodb --parameter-overrides DynamoDBTableGlobalName="fmarc-academy-global-cf" DynamoDBTableJobsName="fmarc-academy-jobs-cf" --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - echo "End Build"