version: 0.2

phases:
  install:
    commands:
      - echo "Start install"
      - echo  $(date)
      - echo "End install"

  build:
    commands:
      - echo "Start Build"
      - echo  $(date)
      - echo "End Build"
 