version: 0.2

phases:
  install:
    commands:
      - echo "Start Install"
      - echo $(date)
      - echo "End Install"

  build:
    commands:
      - echo "Start Build"
      - echo $(date)
      - aws cloudformation deploy --template-file CICD/s3.yml --stack-name fmaric-s3 --parameter-overrides S3BucketData=BucketData S3BucketScripts=BucketScripts --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - aws cloudformation deploy --template-file CICD/dynamodb.yml --stack-name fmaric-dynamodb --parameter-overrides DynamoDBTableGlobalName=tableGlobal DynamoDBTableJobsName=tableJobs --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - echo "End Build"
