AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with specified tags

Parameters:
  S3BucketData:
    Description: Name of the S3 bucket to store data
    Type: String

Resources:
  DataBucket:
    Type: 'AWS::S3::Bucket'
    Properties: 
      BucketName: "fmaric-academy-aws-cf"
      Tags:
        - Key: Owner
          Value: "fmaric"

Outputs:
  DataBucketName:
    Description: Name of the S3 Data Bucket
    Value: !Ref DataBucket